### ISSUE TITLE
Register Global Slash commands

### ISSUE THREAD

**Issue by Ampferl** [THI-CSI/discord-bot#5]
### [USERS] /authenticate <TOKEN>

Tokens are being distributed to the first-semester students. 

### [ADMIN] /sweep <SELECTABLE: {TOKENS, USERS}> <SELECTABLE: "timeframe" {1d. 3d. 7d. 2w. 1month}>

**Comment by bee1850** [comment]
Will add /authenticate first - rather make it a guild specific slash command though, so its registered on Guild add.
