### ISSUE TITLE
Create database table "tokens"

### ISSUE THREAD

**Issue by Ampferl** [THI-CSI/discord-bot#6]
id : AUTO_INCREMENT | token : STRING | targetRole : DISCORDROLEID | comment : STRING | createdAt : DATE | usedAt : DATE

token [A-Z0-9] - 6 digits

**Comment by Ampferl** [comment]
Implemented in Commit c84b224868136ce14f4feb67ea4474d7f9a7b68e

**Comment by bee1850** [comment]
Updated in f066594eba00a80d3a6a4f9557b9a2e068fb7cbe

**Comment by Ampferl** [comment]
We should drop the tokenId as PRIMARY_KEY and use the token itself as identifier @bee1850

**Comment by bee1850** [comment]
I will look into it.

**Comment by bee1850** [comment]
#10

**Comment by bee1850** [comment]
Issue was resolved. See #10 for possible token generation queries.
